services:
  - type: web
    name: line-openai-bot
    env: node
    runtime: node
    buildCommand: npm install --production
    startCommand: node my-line-bot/index.js
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
