services:
  - type: web
    name: line-openai-bot
    env: node
    buildCommand: npm clean-install
    startCommand: npm start
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
